---
- name: This my web server installation playbook
  hosts: CSS
  vars:
   apache_port: 80
  become: yes

  tasks:
  - name: Install the HTTPD package
    package:
      name: apache2
      state: present
  
  - name: Update the apache configuration
    template:
      src: ports.conf.j2
      dest: /etc/apache2/ports.conf
    notify:
    - Restart service

  - name: Copy Web content
    copy:
      src: index.html
      dest: /var/www/html/
  
  handlers:
    - name: Restart service
      service:
        name: apache2
        state: restarted
